name: Waka Readme

on:
  push:
    branches:
      - main
  schedule:
    # every 10 minutes
    - cron: '10 * * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: 'False'
          SHOW_OS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_TIMEZONE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_LOC_CHART: 'False'
          SHOW_LANGUAGE_PER_REPO: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_LINES_OF_CODE: 'True'
          SHOW_TOTAL_CODE_TIME: 'True'
